### PR TITLE
Grocery UI template for flutter

### PR DESCRIPTION
**Pull request by vishalkevin11**
# Description

Added grocery UI template, Has 2 screens
- Dashboard or landing screen
- Item Details screen

# Demo
grocery-app-template

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Manual testing

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by vishalkevin11** [comment]
@SmartAree Could you please review the above PR? This PR is for adding a grocery UI.

**Comment by areeba-farooq** [comment]
But why are you adding this here?? you have to do it in the original repository

**Comment by vishalkevin11** [comment]
My bad, I should have seen this.

**Comment by areeba-farooq** [comment]
@vishalkevin11  its ok :>

**Pull request closed without merging**
